### ISSUE TITLE
Is it possible to reuse your code?

### ISSUE THREAD

**Issue by miltonlm** [RTMadao/SF-service-electronic_invoice#1]
Hi @RTMadao ,

I am looking to implement a DIAN client for sending invoices.
I was looking at your code and it seems that you have it already done. Can we chat?

**Comment by pipegoods** [comment]
I need too, where can i contact you?

**Comment by miltonlm** [comment]
> 

Hi @pipegoods chat me on WhatsApp at +507 6894 3233

**Comment by RTMadao** [comment]
Hi  @miltonlm, 

Anyone can reuse the code acording to the project's License, **Apache License 2.0**. 

The project is not finished yet, some features are missing, like send the generated attached document and build some alternative paths specified by DIAN, but you can use what you need. Also, improvements to the code will always be well received.
